# Generated by Django 4.2.28 on 2026-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card_transfer', 'Card Transfer')], default='cash', max_length=20),
        ),
    ]
